package com.microservice.SAPCommentService.model;

import jakarta.persistence.*;
import lombok.Data;

/*
 * This is the model class for the comments table in the database.
 * It has the following fields:
 * - commentId: the id of the post which will generated by the database
 * - postId: post id a foreign key to the posts table
 * - authorId: author id a foreign key to the users table
 * - content: the content of the comment
*/

@Entity
@Data
@Table(name = "comments")
public class Comment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "comment_id")
    private Long commentId;

    @Column(name = "post_id")
    private Long postId;

    @Column(name = "author_id")
    private Long authorId;

    @Column(name = "content")
    private String content;
}
