spring:
  application:
    name: SAP-Comment-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/COMMENT
    username: comment
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083